### ISSUE TITLE
Navigate to Slack room from search results

### ISSUE THREAD

**Issue by matthew-piziak** [emacs-slack/emacs-slack#473]
`slack-search-from-messages` works great in that it finds message results matching my queries. It also nicely includes the room names, author names, and timestamps.

However, I do not see how to see where they came from. Could the results allow me to navigate to the room and position where they originated?

**Environment:**
 - OS: NixOS
 - Emacs Version: 27.0.50
 - emacs-slack Version: df605f4

**Comment by prosoitos** [comment]
I agree that this would be a huge enhancement without which this search feature is a little limiting. Thanks!!

**Comment by prosoitos** [comment]
Thanks ag91 for working on this.

`slack-search-result-open-message` does open the right message chat, but it opens it at the very end (at least in my tests) instead of navigating to where the message from the search result originated from.

For instance, I do a search and find an entry from 4 years ago. I press RET on it and it opens the right chat but at the very end of the conversation. I then have to manually scroll back and load hundreds of pages until I finally reach the location of the search result.

Any way to have RET navigate to the actual post of the search result? That would be extremely useful.

Thanks!

**Comment by ag91** [comment]
actually I would like that as well. The obstacle is that at the moment the buffers are built to only go up (in the sense they load the most recent  messages and let you load the older ones).
They should instead support bidirectional navigation (see older, see newer) and anchor over the selected message (your search result).
I don't think is a hard task but may be an endeavor because we have:
1. list all the places that would benefit (slack-buffer, activity-buffer, ??)
2. implement a mechanism to hold a message pointer and load more both ways
3. check how we can achieve that via the API (that is easy as it is documented)
4. implement the load more in the various places

I could try actually, but is the time I miss.

**Comment by prosoitos** [comment]
No problem! Thanks for all the work you are doing already!!! ❤
