### ISSUE TITLE
Excessive thread notifications

### ISSUE THREAD

**Issue by ieure** [emacs-slack/emacs-slack#512]
**Describe the bug**

I'm getting notifications for every thread (and reply within it) for every room I'm in.

**To Reproduce**
1. `(setq slack-buffer-create-on-notify t)`
2. Wait for someone to create a thread, and someone to reply to it.
3. You will see notifications (if you're using `alert`) and buffers created for the new thread, even though you took no action.
4. Kill the buffer with the thread.
5. If someone replies to the thread, the thread buffer is recreated and you're notified again.

**Expected behavior**
 - I only get notifications/new messages for threads I've explicitly opened with `slack-thread-show-or-create`.
 - There should be some way to explicitly stop receiving notifications for a thread.  I looked and didn't find anything obvious.

**Environment:**
 - OS: Debian Buster
 - Emacs Version: GNU Emacs 26.1
 - emacs-slack Version: d53a57a.  Something in between 009e48b...d53a57a changed this behavior.

**Comment by ieure** [comment]
Okay, I found `slack-message-unfollow`, if I put point on the `1 reply from whoever` line in the thread buffer and run it, I get:

`[2020-04-13 08:20:46] [info] [TheSlackGroup] Successfully unfollowed.`

But even if I do that and kill the thread buffer, it comes back the next time a thread reply is posted, and notifies me in the modeline via `alert`.

**Comment by emin63** [comment]
Any update on this? I have what I think may be a related question.

The emacs slack client seems to prevent the desktop client from showing unread messages properly in the sidebar. That is, if I subscribe to channel abc on the emacs slack client and someone sends a message to channel xyz, the desktop client won't show that I have an unread message in channel xyz.

How can I make it so that I can subscribe to channel abc in the emacs slack client and use the desktop client to interact (and track read/unread status) in others channels?

Btw, thanks @yuya373 for this neat software.

**Comment by ieure** [comment]
I've actually decided that I like seeing everything that happens, and don't want this fixed.  Or would like a fix which gives the option for either behavior.

**Comment by ag91** [comment]
I will close this, but I am open to PR.
> How can I make it so that I can subscribe to channel abc in the emacs slack client and use the desktop client to interact (and track read/unread status) in others channels?

I think the websocket notification of receiving a message affects the browser client, so I don't think there is a way to avoid it unless you disable the websocket of emacs-slack (which makes it less interactive)
